### ISSUE TITLE
Haneefa bio

### ISSUE THREAD

**Issue by Haneefa-Shaik** [lab-brussels-1/Group-1-Project-Management#5]
- [x] this feature is developed in a branch called 'Haneefa-Shaik'
- [x] created file 'haneefa-shaik.md'
- [x] add info about Haneefa-Shaik
- [x] check if my file passes the different scripts
- [x] add my file
- [x] commit
- [x] push
- [x] create a PR

**Comment by bermarte** [comment]
`Haneefa-Shaik.md` will not pass the workflow, don't use capital letters

**Comment by Haneefa-Shaik** [comment]
yeah @bermarte . thank you and i am sure that i wont repeat this mistake again.

**Comment by Haneefa-Shaik** [comment]
closed
